<?php
/**
 * NOTICE OF LICENSE
 *
 * This software is under the MIT License
 * Copyright (c) 2012 Michele Marcucci
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * @license     http://opensource.org/licenses/mit-license.php The MIT License (MIT) 
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body>

<?php echo $this->getChildHtml('after_body_start') ?>

<!-- Main Wrapper -->
<div id="wrapper" class="container ">
	<div class="my-account" style="background-image: none; padding-bottom: 0px;">
		<div class="account-wrp">
			<div class="blocco-notes">
				<div class="scheda">
					<div class="info">
						<div class="txt">
							<div class="account-login">
								<div class="page-title">
									<h1>Effettua il Login</h1>
								</div>
								<form action="<?php echo $this->getUrl("uservoice/index/loginPost") ?>" method="post">
									<input type="hidden" name="returnUrl" value="<?php echo $this->getRequest()->getParam('return'); ?>" />
									<table>
									    <tr>
									    	<td><label>Username</label></td>
									    	<td><input type="text" id="modlgn_username" name="login[username]" value="" /></td>
									    </tr>
								    	<tr>
								    		<td><label>Password</label></td>
								    		<td><input type="password" id="modlgn_passwd" name="login[password]" value="" /></td>
								    	</tr>
									    <tr>
									    	<td colspan="2"><button type="submit" class="login">Login</button></td>
									    </tr>
								    </table>
								</form>
								<p><br />Non sei registrato? <a href="<?php echo $this->getUrl("customer/account/create") ?>" target="_BLANK">Registrati qui</a>.</p>
							</div>
						</div>
					</div>
				</div>
				<div id="account-shadow"><div class="sx"></div><div class="dx"></div></div>
			</div>
		</div>
	</div>
</div>

</body>
</html>

